version: '3.9'

services:

    backend:
        container_name: fastapi
        user: root
        build: ./backend
        ports:
            - "5000:5000"

    frontend:
        container_name: vue
        build: ./frontend
        volumes:
        - './frontend:/app'
        - '/app/node_modules'
        ports:
        - 8080:8080

